version: "3"
services:
  db:
    image: mongo
    container_name: db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: dev
    command: [--auth]
  backend:
    build: .  
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      DB_NAME: 'dev'
      HOST: 'localhost'